### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by MiguelG97** [IFCjs/components#89] opened 2023-07-23 05:00 UTC
### Describe the bug 📝

when initializing the components from the boilerplate code I receive a Maximum call stack size exceeded RangeError:
![image](https://github.com/IFCjs/components/assets/78984964/89596874-d137-40cc-8870-2fef96ba09d8)

I'm using the boilerplater :
```
// Initialize the basic components
const container = document.getElementById("container");
const components = new Components();
//console.log(components);
components.scene = new SimpleScene(components);
components.renderer = new SimpleRenderer(components, container);
components.camera = new SimpleCamera(components);
components.raycaster = new SimpleRaycaster(components);
components.init();

// Add some elements to the scene
const scene = components.scene.get();

const geometry = new BoxGeometry(3, 3, 3);
const material = MeshStandardMaterial({ color: "red" });

const cube = new Mesh(geometry, material);
cube.position.set(0, 1.5, 0);
scene.add(cube);

components.meshes.push(cube);
```

Dependencies
![image](https://github.com/IFCjs/components/assets/78984964/385727c2-7add-461b-88a4-7484dae8eb7b)

### Steps to reproduce 🔢

Type the boilerplate
execute the init() command from the component class

### System Info 💻

```shell
--sytem
```

### Used Package Manager 📦

npm

### Error Trace/Logs 📃

 Uncaught RangeError: Maximum call stack size exceede

### Validations ✅

- [X] Read the [docs](https://ifcjs.github.io/info/docs/Introduction).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a IFC.js components issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/FXfyR4XrKT).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment] 2023-08-04 09:00
Hey, can you provide a minimal app where we can reproduce it? What browser are you using?

**Comment by MiguelG97** [comment] 2023-08-08 05:43
Hi anton! It was deployed on google chrome. Sure I will provide one sooner

**Comment by sjovanovic** [comment] 2023-08-23 13:52
I encountered this error a lot when parsing ifc files. (I just call  `ifcapi.StreamAllMeshes(modelID, (flatMesh)=>{ })` )
In Nodejs if I increase the stack with `--stack-size` option it works. 
But on some of the files when I increase the stack the error just changes to "Segmentation fault: 11"

**Comment by agviegas** [comment] 2023-11-01 16:54
I'm closing this for now as we couldn't reproduce this. Let us know if this keeps happening with the latest version and you can provide a way for us to reproduce it!

**Closed by agviegas** 2023-11-01 16:54 UTC
Labels: bug

**Comment by vulevukusej** [comment] 2023-12-07 08:00
@agviegas I have a file which causes this issue as well, and the error occurs when using https://platform.thatopen.com/app as well.  Can I share the file privately?
