### ISSUE TITLE
SimpleClipper bug

### ISSUE THREAD

**Issue by SBrida** [IFCjs/components#130] opened 2023-10-05 14:33 UTC
### Describe the bug 📝

Hello , after Updating the version of three.js and openbim-components : 

npm i openbim-components@1.1.1 --save-exact

npm i three@0.152.2 --save-exact  

the Simple Clipper seems work  perfectly but when you start the code by :

clipper.enabled = false;

the plane and the arrows will not hidewhen you click on that icon to disable it ... 

snippet bellow from the example of github i change it from true to false and this is the result 

### System Info 💻

```shell
npm i openbim-components@1.1.1 --save-exact

npm i three@0.152.2 --save-exact
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://platform.thatopen.com/documentation).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a IFC.js components issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by HoyosJuan** [comment] 2023-11-29 04:30
Hey @SBrida! This seems to be working perfectly fine from my side using openbim-components1.1.6. Would you mind testing it and tell me if the issue still happen to you?

**Comment by SBrida** [comment] 2023-11-30 19:11
Hey @HoyosJuan , Thanks for reply. 
Still the same. i updated to 1.1.6
when i begin the code with the clipper.enable =false 
after working with clipper and i want to disable it . the arrow still there... 
![Screenshot 2023-11-30 200521](https://github.com/IFCjs/components/assets/147074562/568ca5c3-274a-4cf9-a0fa-d1f618512135)

**Comment by SBrida** [comment] 2023-11-30 19:25
@HoyosJuan i just figure it out : 
clipper.enabled = false
clipper.visible = false

must begging with both

**Comment by HoyosJuan** [comment] 2023-11-30 19:54
Hmm @SBrida, but stills weird as that's not the expected behavior 🤔 I will look at it again and if everything is ok, then I will close the issue. 

Are you ok with that? 🙂

**Closed** 2023-12-01 16:48 UTC
Labels: bug
